### ISSUE TITLE
关于计算器

### ISSUE THREAD

**Issue by Tback1** [goreliu/runz#10]
不知道AHK下实现自动识别算式的难度

暂时觉得先calc 再回车 再去输入算式这个要从大键盘区移到小键盘区挺反效率的

不知道能不能自动根据输入算式识别为计算模式

1.比如识别到有+-*/这些符号就自动进入calc模式
2.或者连续2位输入是数字进入calc模式？（有些软件也有两位数字名，容易失误）
或者别的更快捷一些的想法？

**Comment by goreliu** [comment]
在输入内容没有匹配到结果时，自动检测是否可以计算，如果可以就调用计算器直接显示，这样如何？
检测的话就直接算一次，如果不是 0 就认为可以算，如果能算但结果也是 0 就没办法了，比如 0+0 这种检测不出来，不过这样检测出来意义也不大。

**Comment by Tback1** [comment]
当然很棒啊～只是不知道会不会造成卡顿，毕竟多了一个大范围匹配识别的，只匹配+-*/四种符号递归的负担没那么大

**Comment by goreliu** [comment]
只在搜索无结果时算，应该还好。而且现在运行 calc 回车，计算就是实时的，应该也感觉不出来卡顿。

**Comment by Tback1** [comment]
那就等加上了测试评估一下把～～·

**Comment by goreliu** [comment]
已经改好了，1.0.10 版本，可以试一下。

**Comment by Tback1** [comment]
新版本测试毫无问题。上次残留bug已解决
另外新计算器很好用～
不过有个小bug，完全不影响使用，仅仅备忘，以免类似问题出现找不到参考
输入445 在输入+-*/前只能只能识别出44，不影响进一步输入

![image 4](https://cloud.githubusercontent.com/assets/8872546/14768113/3cb3b520-0a6b-11e6-94b0-4c58a0656a21.png)

**Comment by goreliu** [comment]
我在输入 445 时，会直接显示 445。

**Comment by Tback1** [comment]
晚点找个软件录屏，我还是能重现这个有趣的bug。而且我测试过其他数字都不会出这毛病，偏偏是445这个组合。这个是不是和本地索引的东西有关？

2016-04-25 7:31 GMT+08:00 Gore Liu 陌辞寒 notifications@github.com:
