### ISSUE TITLE
配置文件的 SearchFileDir 属性值无法识别 (即, 无法添加目录)

### ISSUE THREAD

**Issue by wenmin92** [goreliu/runz#17]
`RunZ` 的默认的配置是:

```
  SearchFileDir=A_ProgramsCommon | A_StartMenu
  ; 搜索的目录，可以使用 全路径 或 ahk 以 A_ 开头的变量，必须以 " | " 分隔
  SearchFileType=*.lnk | *.exe
  ; 搜索的文件类型，必须以 " | " 分隔
```

按说应该可以检索到以下两个目录中的 `*.lnk` 文件啊: 

> C:\ProgramData\Microsoft\Windows\Start Menu\Programs
> C:\Users\current_user\AppData\Roaming\Microsoft\Windows\Start Menu\Programs

但是, 我这里就是什么都不能检索到.
按照 [用户手册 #3.添加目录](https://github.com/goreliu/runz/wiki/%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C#3-%E6%B7%BB%E5%8A%A0%E7%9B%AE%E5%BD%95) 的说明, 我在D盘创建了 `D:\test` 目录, 并放置了一些 `*.lnk` 文件, 然后 `Ctrl + R`, 右键重建索引, 重启之后, 都无法检索到.
只有使用右键发送到 `RunZ` 这种方法可以成功检索到, 但是由于这种没法添加目录, 所以这个问题还是非常有必要解决的.

**Comment by goreliu** [comment]
改完的配置发上来看下。另外看下 `Conf\SearchFileList.txt` 文件里有没有待搜索的文件路径。

**Comment by wenmin92** [comment]
@goreliu 
这是我的配置文件, [RunZ.ini.txt](https://github.com/goreliu/runz/files/274079/RunZ.ini.txt). 
另外我貌似没有 `Conf\SearchFileList.txt` 这个文件.
我的 `Conf` 目录结构是这样的: 

```
~RunZ\Conf
|   README.txt
|   RunZ.auto.ini
|   RunZ.ini
|   RunZ.ini.help.txt
|   UserFileList.txt
|   UserFunctionsAuto.txt.template
|
\---Skins
        Background.jpg
        Background1.jpg
        Background2.jpg
        Default.ini
        New.ini
```

**Comment by goreliu** [comment]
不好意思，猜不出什么原因，正常情况都会生成这个文件。
