### ISSUE TITLE
可以用数字键选择吗

### ISSUE THREAD

**Issue by sishentibu** [goreliu/runz#18]
默认配置中，选择是按 Alt+字母 来选择的

我自己用的软件快捷方式基本都是字母，因此想要改成单键数字选择。这个可以实现的吗？
如果可以的话，应该修改哪里？

**Comment by zichenw** [comment]
Alt+字母真的很别手，老大求回复

**Comment by goreliu** [comment]
可以，配置文件里，

```
FirstChar=1
; 列表第一行的首字母或数字
```

改成 1 就行，然后 DisplayRows 改成 10。

**Comment by sishentibu** [comment]
@goreliu 这么改之后，需要用alt + 数字，是比原来的用字母顺手多了。
单键数字是否不好设置？

**Comment by goreliu** [comment]
单键的话得先按 Tab 把焦点从编辑框移走。
