### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by iceloon** [goreliu/runz#2]
有点bug， ipconfig 或者cmd ipconfig 打开的界面闪一下就自动关闭了

**Comment by goreliu** [comment]
@iceloon 
如果直接输入 ipconfig，会用 ahk 的 Run() 调用，效果就是一闪而过。如果要在 cmd 运行并暂停，可以前边加冒号`:ipconfig`。使用 cmd ipconfig 默认也会匹配到 ahk 的 Run()，可以通过调权重把第二个 CmdRun 调上去，cmd ipconfig 就和 `:ipconfig`效果一样了。

我在新版已经让输入 cmd xxx 默认匹配到 使用 cmd.exe 运行了。

默认使用 ahk 的 Run() 运行，是因为它支持直接打开网址等功能，比 cmd 要强大一些。

**Comment by goreliu** [comment]
如果想要默认使用 cmd.exe 运行，可以改代码（不支持改配置文件）。

`Core\Functions.ahk` 文件，把 CmdRun 移动到 AhkRun 前边，如果想默认使用`Win + r`运行，可以把 WinRRun 放到最前边。

```
Functions:
    @("Help", "帮助信息")
    @("KeyHelp", "置顶的按键帮助信息")
    @("AhkRun", "使用 Ahk 的 Run 运行 `; command", true)
    @("CmdRun", "使用 cmd 运行 : command", true)
    @("WinRRun", "使用 win + r 运行", true)
```

**Comment by iceloon** [comment]
@goreliu  谢谢，我再慢慢研究。非常感谢提供这么实用小巧的工具！
