### ISSUE TITLE
我用ps命令回车后怎么界面是这样的？

### ISSUE THREAD

**Issue by teraStars** [goreliu/runz#20]
我用ps命令回车后怎么界面是这样的？
![qq 20160603221742](https://cloud.githubusercontent.com/assets/7426499/15781561/49a94d16-29d9-11e6-82a0-067d87d199a1.gif)

**Comment by goreliu** [comment]
我这里复现不出来，每次都这样吗？

**Comment by teraStars** [comment]
最新版已经没这问题了。
