### ISSUE TITLE
像“js”这些alias是在哪里定义的？

### ISSUE THREAD

**Issue by h46incon** [goreliu/runz#24]
比如我搜索“js”的时候，也会匹配到“calc”，请问这种alias可以自己定义吗？

**Comment by h46incon** [comment]
RunZ真是挺好用的，试用了几分钟后就把我用了几年的FARR关了……

**Comment by goreliu** [comment]
如果是直接能搜到，但不排在第一个的，可以用上下键定位到要调到第一个的那个命令，然后`ctrl+n`把权重调大。如果是搜不到的，可以在配置文件里边加。

**Comment by h46incon** [comment]
呃这个要怎么在配置文件里添加呢？

**Comment by h46incon** [comment]
呃这个要怎么在配置文件里添加呢？
还有现在RunZ自带的这些是在哪里添加的呢？

**Comment by h46incon** [comment]
呃这个要怎么在配置文件里添加呢？
还有现在RunZ自带的这些是在哪里添加的呢？

**Comment by goreliu** [comment]
```
[Command]



; 这里的 command 优先显示
;
; 文件类型（直接使用 AHK 的 Run() 运行）：
; file | 文件路径 | 注释
; 如：
; file | notepad | 记事本
; 注释里可以包含要搜索的字符串，也可以没有：
; file | c:\mine\mine.exe
```

注释里可以写自己的 alias。自带的一部分是在开始菜单等地方搜到的文件，一部分是内置的功能。

**Comment by h46incon** [comment]
哦哦，明白了。谢谢！
