### ISSUE TITLE
GUI 的设置选项如果能更加细致那就爽歪了

### ISSUE THREAD

**Issue by dmscode** [goreliu/runz#25]
比如：
每个区域的字号可以单独设置
每个区域的背景色、背景透明度、边框颜色可以单独设置
GUI 的透明度
背景图片填充方式、对齐方式
……
这样就可以自定义出更加美观的界面了。

---

然后，字号设置为 16，而输入框高度设置为 48 （以上）的时候，输入框右侧出现滚动条……好尴尬

**Comment by dmscode** [comment]
二维码可否加一个保存按钮？蜜汁尴尬

**Comment by goreliu** [comment]
界面暂时不会变了，直接点二维码就可以保存。

**Comment by dmscode** [comment]
感谢解答~~
