### ISSUE TITLE
切换窗口不方便

### ISSUE THREAD

**Issue by nick357** [goreliu/runz#26]
我觉得快速启动和切换窗口都是非常实用的功能，但快速启动类工具一般都没提供切换窗口的功能。
在runz这个工具里有这个功能但用起来十分不方便。
我查阅了使用手册目前只能通过 ListWindow ，（Ctrl+Enter）复制到剪切板，在ActivateWindow。
不知道是不是我使用方式不对。而且这种方式有个问题就是用explorer.exe打开多个文目录时总是切到第一个激活的窗口，无法精准的切换到想要的窗口。
能不能做到像启动任务一样，列出窗口选中回车或快捷键选择就能切换过去。
有个开源的切换窗口的工具http://www.switcheroo.io/ ，不是特别好用，可以查考下。
另外十分感谢你能开源这么好的工具给大家用。多谢！

**Comment by goreliu** [comment]
这个功能只是为了演示 RunZ 自身的功能，实用性并不大。运行 ListWindow 后，可以继续搜索（比如输入 explorer.exe 打开的目录名）匹配到唯一的窗口，然后 Ctrl + Enter 激活。

**Comment by nick357** [comment]
操作十分繁琐，而且窗口会有大幅度的闪动现象，有考虑实现快速切换窗口之类的插件吗。列出窗口后输入标题或路径的一部分回车直接切换（能有列表快捷键就更好了）。windows切换任务的功能其实感觉蛮弱的。但快速启动任务的工具很多，切换窗口这块好像没什么好用的工具。

**Comment by nick357** [comment]
切换不成功，而且窗口会有大幅度的闪动现象，有考虑实现快速切换窗口吗。列出窗口后输入标题或路径的一部分直接切换。

**Comment by nick357** [comment]
切换不成功，而且窗口会有大幅度的闪动现象，有考虑实现快速切换窗口吗。列出窗口后输入标题或路径的一部分直接切换。

**Comment by nick357** [comment]
切换不成功，而且窗口会有大幅度的闪动现象，有考虑实现快速切换窗口吗。列出窗口后输入标题或路径的一部分直接切换。

**Comment by nick357** [comment]
切换不成功，而且窗口会有大幅度的闪动现象，有考虑实现快速切换窗口吗。列出窗口后输入标题或路径的一部分直接切换。

**Comment by nick357** [comment]
操作比较复杂，而且窗口会有大幅度的闪动现象，有考虑实现快速切换窗口吗。列出窗口后输入标题或路径的一部分直接切换。

**Comment by nick357** [comment]
操作比较复杂，而且窗口会有大幅度的闪动现象，有考虑实现快速切换窗口吗。列出窗口后输入标题或路径的一部分直接切换。

**Comment by nick357** [comment]
操作比较复杂，而且窗口会有大幅度的闪动现象，有考虑实现快速切换窗口吗。列出窗口后输入标题或路径的一部分直接切换。

**Comment by goreliu** [comment]
不考虑这个功能，可以找找有没有专门的工具。

**Comment by nick357** [comment]
好的，感谢
