### ISSUE TITLE
想用Ctrl+打开

### ISSUE THREAD

**Issue by kimihiro233** [goreliu/runz#27]
默认用alt+space打开窗口，个人觉得按两下Ctrl更方便一点，但是设置改了配置没有用，可以帮忙看一下吗？

**Comment by goreliu** [comment]
不能设置成用两下 Ctrl。

**Comment by cnwayne** [comment]
alt+space 覆盖了windows窗口快捷键，这可是键盘党的常用快捷键啊！！
