### ISSUE TITLE
cmd命令会弹出多个窗口

### ISSUE THREAD

**Issue by Leoongithub** [goreliu/runz#29]
操作如下：
Alt+空格唤醒程序，输入cmd命令(如": dir"或:"cmdrun dir")，回车，然后会弹出6个cmd窗口。

**Comment by goreliu** [comment]
不好意思一直没有回复，无法复现。

**Comment by Leoongithub** [comment]
其实并不是每次都会出现6个，实际出现过1~6个不等，根据按键触发的情况看，似乎是有时会触发多次enter
![a](https://user-images.githubusercontent.com/10937162/30237117-96485248-955d-11e7-9326-a9be2d5ef4eb.gif)
如上图所示，实际上每次我都只按了一次enter

**Comment by goreliu** [comment]
如果按了多次回车确实可能有这种现象，我再看下。

**Comment by goreliu** [comment]
可以先把 RunZ.ahk 的 1105 行注释掉试试：

```
        ;Send, {enter}
```

**Comment by Leoongithub** [comment]
这个方法可以解决问题

**Comment by goreliu** [comment]
那大概知道是什么原因了，我再想想怎么改下。

**Comment by goreliu** [comment]
看起来把那三行去掉就行了，没有什么负面影响。之前是因为处理中文输入法相关的问题加的，但实际上没有什么意义。
