### ISSUE TITLE
输入命令时是否可以更模糊一些

### ISSUE THREAD

**Issue by dehere** [goreliu/runz#31]
比如我有个程序的名字是"HD Tune  v5.60.exe"，如果直接输入hdtune，则找不到这个文件。
用上下箭头选择命令时，是否可以将当前的命令颜色加深？字体放大总觉得不是特别明显。
感谢您的这款软件，之前用过altrun和almrun，但这两个在win10下面总有些不兼容。

**Comment by goreliu** [comment]
tcmatch 是按空格分词的，这个没办法做。上下箭头会移动大于号，编辑框加深不了颜色。
