### ISSUE TITLE
可以隐藏通知栏图标吗？

### ISSUE THREAD

**Issue by mkitby** [goreliu/runz#32]
我想隐藏通知栏图标，这种利器平常是看不到的，关键时刻出现，然后消失于无形。

**Comment by lirtual** [comment]
配置文件有通知栏图标显示的设置。

**Comment by mkitby** [comment]
我没找到啊，哪一句，我用的v1.1.0

**Comment by lirtual** [comment]
在初始配置文件中的第70行。

```properties
ShowTrayIcon=1
; 是否显示托盘图标
```

或者你可以使用Ctrl+F查询`ShowTrayIcon`，然后将值改为0即可 。

**Comment by mkitby** [comment]
非常感谢，可以隐藏了
