### ISSUE TITLE
可不可以自定义名称

### ISSUE THREAD

**Issue by mkitby** [goreliu/runz#33]
比如打开一个软件 photoshop, 直接输入ps

**Comment by lirtual** [comment]
其实专门提供用户自定义文件列表的配置文件，只需要在`Runz\Conf\UserFileList.txt`里面添加就可以了。

格式：
file | 目标程序绝对路径  |  搜索/显示关键字

举例：
file | D:\Program Files\Adobe\Adobe Photoshop CS6 (64 Bit)\Photoshop.exe  | ps

如果觉得这样麻烦，还有一个稍微偷懒点的方法。

只需要找到你要自定义名称的程序，然后**鼠标右键**-**发送到**-**Runz**。

会在UserFileList.txt中添加 `file | 目标程序绝对路径  | ` ，不包含关键字，自己再手动添加即可。

试试能否搜索，如果没有就**重建索引**。

**Comment by mkitby** [comment]
搜索匹配功能感觉有问题，输入sf，原本是想运行dedipro, 结果显示这么多选项

a>| 功能 | ShowService                                   | 显示服务详情
b  | 文件 | dedipro                                           | sf
c  | 文件  | Bluetooth File Transfer Wizard       |
d ...
e...
f...

**Comment by lirtual** [comment]
这个似乎没有很好的解决方法，因为模糊搜索出来的结果不唯一，不过它会根据你的使用频率排序搜索结果。

建议：只能听过Tab+字母打开，或者多用几次，自然就排在第一位直接Enter。

**Comment by goreliu** [comment]
不好意思一直没有回复。

sf 匹配到了“示服”和“Transfer"里的“sf”，可以把 dedipro 的优先级用 ctrl + n 提升（先按下方向键，选到 dedipro）。
