### ISSUE TITLE
与其他AHK - CapsLock Enhancement的联动冲突

### ISSUE THREAD

**Issue by VimWei** [goreliu/runz#35]
我使用CapsLock Enhancement（  https://github.com/Vonng/Configuration/tree/master/win  ），其中定义了如下全局设置和热键：
SetCapsLockState, AlwaysOff
CapsLock & j:: Send, {Down} 
CapsLock & k:: Send, {Up} 

期待的效果是同时使用RunZ和上述AHK时——CapsLock & j触发{Down}，{Down}再触发RunZ的"Hotkey, Down, NextCommand"，从而取代RunZ的快捷键^j。但实际运行时，在RunZ的搜索框中使用CapsLock & j，并未出现预期效果（NextCommand），而是仅在搜索框向右移动（类似Send, {Right}）。

为此，我又尝试了如下几种解决方案：
1、直接添加如下代码到RunZ.ank，但这样会导致RunZ无法运行。
SetCapsLockState, AlwaysOff
CapsLock & j:: Send, {Down} 
CapsLock & k:: Send, {Up} 

2、在RunZ.ini的[Hotkey]中添加如下代码:
CapsLock & j=NextCommand
CapsLock & k=PrevCommand

若仅运行RunZ，可以实现预期的上下移动效果，但若同时运行RunZ和CapsLock Enhancement，就会导致CapsLock Enhancement的功能完全失效（在非RunZ环境中也一样失效），如：
SetCapsLockState, AlwaysOff
CapsLock & j:: Send, {Down} 
CapsLock & k:: Send, {Up} 

自己试验了几次，感觉是两个AHK对CapsLock键的定义有冲突，只能一者存在。
请教，如何才能让定义CapsLock & j和CapsLock & k取代默认的^j和^k，而又不与其他AHK冲突。

**Comment by VimWei** [comment]
补充说明，上述RunZ的版本是直接下载master的clone or download。
现更换了RunZ版本为RunZ 1.1.0 (2016-08-22)，并执行RunZ.exe，情况有所变化：
期待的效果是同时使用RunZ和CapsLock Enhancement 的AHK时——CapsLock & j触发{Down}，{Down}再触发RunZ的"Hotkey, Down, NextCommand"，从而取代RunZ的快捷键^j。**但实际运行时，在RunZ的搜索框中使用CapsLock & j，并未出现预期效果（NextCommand），而是在搜索框直接输入j，也就是直接忽视CapsLock Enhancement 中的CapsLock & j热键。**

这应该是不正常的bug，我认为正常的效果至少是：CapsLock & j触发CapsLock Enhancement 的CapsLock & j热键，输出 {Down}，但在RunZ的编辑框中没有任何输出。这中情况应该普适于所有单行编辑器，如在chrom浏览器地址栏上使用CapsLock & j，就是这样。

**Comment by goreliu** [comment]
不好意思一直没有回复。

尽量不要在 RunZ 里添加好绑定热键相关的代码吧，可能造成类似问题。如果只需要简单的热键定义，可以写 RunZ 的配置文件。
