### ISSUE TITLE
激活后光标位置在输出框

### ISSUE THREAD

**Issue by synhi** [goreliu/runz#36]
我在设置里开启了隐藏界面后清空输入框这个功能
在我用 Esc 键隐藏界面前不小心把光标点到了输出框的位置，再次激活后发现光标还在输出框位置

我的想法是隐藏界面后可以清空输入框并且再次激活的时候光标要在输入框位置，这样能够方便快速的搜索

而且是否可以我执行一个开启程序或者打开文件夹的命令之后自动隐藏软件界面

我还想知道作者是否还在更新，我发现距离上次更新已经过去半年了

**Comment by ShynHan** [comment]
执行一条命令后自动隐藏界面感觉是个很有用的功能，但是又不能执行每条命令之后都隐藏，比如用有道词典翻译的命令，翻译出来的内容是显示在输出区的，如果自动隐藏了会看不到翻译内容，是否可以增加百度翻译功能，因为我发现最近百度翻译也蛮智能的

**Comment by synhi** [comment]
我找到了命令运行一次就推出的设置项了

还有一点建议就是能否百度翻译，就像有道翻译一样，感觉百度翻页也蛮好用的

**Comment by goreliu** [comment]
不好意思一直没有回复。

因为通常不需要用鼠标操作，所以应该很少有光标焦点意外转到输出框的情况,，所以这个自动转换到输入框好像不大合理。

如果想“启程序或者打开文件夹的命令之后自动隐藏软件界面”，可以把配置里的这项打开：

```
ExitIfInactivate=1
; 窗口失去焦点后窗口关闭，启用后窗口置顶显示功能失效
```

**Comment by goreliu** [comment]
我一直在用，但因为不需要更多功能了，所以一直没怎么更新。但如果有问题的话还是会修复的。

关于百度翻译，近期不会考虑，以后的话可能会看看能否实现。

**Comment by wenmin92** [comment]
可不可以设置一个快捷键将焦点定位到输入框？
