### ISSUE TITLE
命令执行完毕后不会自动清空

### ISSUE THREAD

**Issue by ID404** [goreliu/runz#38]
win10 的系统，命令执行完毕后再执行下一条命令时需要先删除上一条命令，比如我要先打开QQ，再打开chrome，目前我需要先输入qq 回车后删除qq再输入chrome。这样操作起来有点麻烦，建议执行命令后自动清空。

**Comment by goreliu** [comment]
把配置文件里的 KeepInputText=1 改成 0 就可以了。如果窗口没有隐藏可以用 ctrl + l 清空。
