### ISSUE TITLE
ControlPanelFunctions建议添加“计划任务”

### ISSUE THREAD

**Issue by Leoongithub** [goreliu/runz#39]
task scheduler

**Comment by goreliu** [comment]
已添加，https://github.com/goreliu/runz/commit/3d818cbeb36510d73732be7fbd74fd92f32ba481

**Comment by Skylarzz** [comment]
1.2.0 输入「计划任务」或「jhrw」没有显示

**Comment by Skylarzz** [comment]
建议将控制面板的所有项与子项，都添加进来

**Comment by goreliu** [comment]
新版本还没有发布。
所有项太多了，暂时没有时间处理，如果你能提供对应命令，我可以加上。

**Comment by Skylarzz** [comment]
如果可以自动搜索控制面板，自动遍历添加的话（就像自动处理某个文件夹一样），就添加一下吧．不过如果需要手动添加的话，就过于锁碎了，不同的系统好像还不一样

一直希望脑海中浮现某个控制面板项，可以直接打开 RunZ 输入拼音首字母，然后回车．

**Comment by goreliu** [comment]
控制面板里可以直接搜索，除了不能用拼音首字母，应该还比较方便。另外控制面板里，不是所有的页面都可以用命令打开的，能找到的我基本已经添加了。
