### ISSUE TITLE
win10下输入法问题

### ISSUE THREAD

**Issue by zhangjie93** [goreliu/runz#4]
win10下使用软件时会默认将输入法改到ENG键盘上，即使将ENG键盘删掉也会被修改

**Comment by goreliu** [comment]
这个是自动切换到英文输入法功能，默认是开启的，可以在配置文件关闭。

右键 -> 编辑配置：

```
SwitchToEngIME=1
; 每次激活窗口自动切换到英文输入法
```

这个改成 0，然后 右键 -> 重新启动 就好了。
