### ISSUE TITLE
输入过快时会导致启动错误的程序

### ISSUE THREAD

**Issue by Leoongithub** [goreliu/runz#40]
例如匹配"ab"的第一个项目是x，匹配"abc"的第一个项目是y，如果快速输入abc并回车，有可能会启动x而不是y

**Comment by goreliu** [comment]
这个比较麻烦，可以要等一阵我再仔细查一下。

**Comment by goreliu** [comment]
确实有这种现象，尝试修复了一下，https://github.com/goreliu/runz/commit/2fc60701fea28b11492501d668c72f5485f5d9bf https://github.com/goreliu/runz/commit/b912307d455c8897b82d38ec8a4b08dec1600cfc
