### ISSUE TITLE
试用了下，挺不错的，以下几个问题帮忙看看，谢谢。

### ISSUE THREAD

**Issue by valuex** [goreliu/runz#41]
1. 失去焦点执行的动作能否和按返回{ESC}保持一致？当前失去焦点后1）没有隐藏任务栏的图标；2）输入的文本仍然存在；
2. 按返回{ESC}后，1）输入框中的内容清空了，但列表中的内容没有刷新；
3. 建议启动或激活窗口后，光标自动聚焦到输入窗口中；当前问题：按下返回{ESC}前，如果光标没有在输入框中，启动或激活界面，光标不会自动聚焦
4. 添加目录没有索引成功，也帮忙看看，配置如下：  
`SearchFileDir=A_ProgramsCommon` | A_StartMenu | F:\Portable 
; 搜索的目录，可以使用 全路径 或 ahk 以 A_ 开头的变量，必须以 " | " 分隔  
; 路径可包含空格，无需加引号  
SearchFileType=*.lnk | *.exe  
; 搜索的文件类型，必须以 " | " 分隔  
SearchFileExclude=卸载 | unis*.exe`

**Comment by goreliu** [comment]
我最近没有时间仔细看，可能要等一阵，不好意思。

**Comment by goreliu** [comment]
因为 AHK 自身的问题，我不打算继续维护当前的 RunZ 了，所以这些问题不再处理了，后续我可能会用其他语言重新一遍。
