### ISSUE TITLE
建议runz中启动了程序后，自动隐藏runz。再次启动runz时，输入框为空。总之希望能和altrun一样就好了。

### ISSUE THREAD

**Issue by fucao** [goreliu/runz#45]
建议runz中启动了程序后，自动隐藏runz。再次启动runz时，输入框为空。总之希望能和altrun一样就好了。

**Comment by goreliu** [comment]
可以在配置文件里修改。

```
KeepInputText=0
; 窗口隐藏时不清空编辑框内容
RunOnce=1
; 运行一次命令就退出，对展示信息的命令无效
```

**Comment by Skylarzz** [comment]
希望可以保留上一次命令，但是处于全选状态．直接回车，可以运行上一次命令，直接输入，也不影响命令的输入

其实我自己写了一个快速运行脚本，就是这么处理的，不过很简陋，希望用 RunZ 取代它

**Comment by goreliu** [comment]
加了，https://github.com/goreliu/runz/commit/c6fb9d0e625b3c2c14a95fda1b842167aa1ab23e
