### ISSUE TITLE
Runz windows can not be shown on firefox interface

### ISSUE THREAD

**Issue by simplesafe** [goreliu/runz#47]
Hi, Thanks so much for your great job! Runz is really of great assitance to me.

I found an issue that: when I opened a firefox window (on the top of desktop) and proceeded to open runz by pressing “#+j”， Runz windows does not appear as normal, after I minimized the firfox window, Runz restored working and appeared. When I works on either Chrome or IE interface, Runz window appears perfect without any problem.
Could you figure out the reason and solution?

PS: Windows 10 / Firefox Quantum 59.0.2 (X64)

**Comment by goreliu** [comment]
I installed [Firefox Quantum 59.0.2 (X64)](https://download-installer.cdn.mozilla.net/pub/firefox/releases/59.0.2/win64/en-US/Firefox%20Setup%2059.0.2.exe), but it seeems working well.

![firefox](https://user-images.githubusercontent.com/169704/39093359-1cdac198-4651-11e8-8334-fe100714e510.png)
