### ISSUE TITLE
关于虚拟机的问题

### ISSUE THREAD

**Issue by Leoongithub** [goreliu/runz#48]
RunZ运行在宿主机时，当窗口的焦点在虚拟机里时会报这种错
![image](https://user-images.githubusercontent.com/10937162/38628487-005dd6ba-3de4-11e8-9585-59ce9a8e0ed6.png)
不清楚是出了什么问题，如果问题比较复杂的话，只要能在vmware窗口下禁用RunZ也可以，不过简单的翻了一下配置文件，好像没有这个功能。

**Comment by Leoongithub** [comment]
另外关于 #45 ，如果上次退出RunZ时光标位于输出栏，这个功能不能达到预期的效果，能否添加激活RunZ时光标自动定位到输入栏的功能？

**Comment by goreliu** [comment]
我没装 vmware ，第一个没办法验证。

但我修改 #MaxHotkeysPerInterval 成 200 了（ https://github.com/goreliu/runz/commit/2a8985b91011fe751832a049d6980a7e106d3b80 ），也许有用。

**Comment by goreliu** [comment]
激活RunZ时光标自动定位到输入栏的功能已添加（ https://github.com/goreliu/runz/commit/0cfe79dba47dd02f4404310702b4b8583f382093 ）。

**Comment by Leoongithub** [comment]
修改了#MaxHotkeysPerInterval之后还是会出现类似的报错，但是不知道为什么，这个问题后来出现的频率变低了（在修改#MaxHotkeysPerInterval之前就变低了），所以这个问题现在不是很影响使用了。
不过还是希望有“在特定窗口下禁用RunZ”的功能，如果比较复杂，不太好加的话就把这个issue关掉吧。

**Comment by goreliu** [comment]
那可以把 200 改大点，比如 1000，直到没有了。

**Comment by goreliu** [comment]
很难改。
