### ISSUE TITLE
有没有办法索引UWP应用

### ISSUE THREAD

**Issue by cinty8b** [goreliu/runz#49]
Win10上使用UWP应用的体验越来越好，很多开发商也提供了软件的UWP版本。
在帮助中没有看到添加UWP应用索引的内容，不知道是不是能做到？

**Comment by goreliu** [comment]
没有办法自动找到，可以手动从开始菜单或者磁铁把图标拖到某个目录。

**Comment by cinty8b** [comment]
拖到目录中，双击快捷方式可以打开，但是把目录添加到runz配置文件后，候选项没有目录里的快捷方式，如果 快捷方式-右键-发送到runz，UserFileList 里只会多一行`file |   | `

**Comment by goreliu** [comment]
需要 ctrl + r 重建索引。

**Comment by cinty8b** [comment]
感谢，问题解决。一直以为“重启”就可以自动更新索引。
