### ISSUE TITLE
关于搜索的目录的设置问题

### ISSUE THREAD

**Issue by mzxhtml** [goreliu/runz#50]
在配置文件里面看到有SearchFileDir里可以写搜索路径的，但是我怎么写都没有用，求解

**Comment by goreliu** [comment]
改完用 ctrl + r 更新。

**Comment by dbsxdbsx** [comment]
@goreliu  您好，我也是同样的问题。我的是win10，配置如下：
```
SearchFileDir= C:\
; 搜索的目录，可以使用 全路径 或 ahk 以 A_ 开头的变量，必须以 " | " 分隔
SearchFileType=*.lnk | *.exe | *.xls | *.xlsx
; 搜索的文件类型，必须以 " | " 分隔
```
重启后并重建索引后，还是不行。
另外，能不能不要设置file type,改为全类型搜索可以吗

**Comment by goreliu** [comment]
@dbsxdbsx everything 应该更适合你的使用场景。
