### ISSUE TITLE
tcmatch 有使用文档吗？

### ISSUE THREAD

**Issue by wenmin92** [goreliu/runz#51]
比如我有一个应用名称为`Android Studio Preview`，我输入`asp`显示不出来，输入`androids`、`androidsp`都不行，反而会出现莫名其妙的东西，只有输入`android`才会出来，请问输入精确得到`Android Studio Preview`。

输入`android`
![image](https://user-images.githubusercontent.com/6901815/39910703-0883957e-552b-11e8-91ac-0481cb2299c7.png)

输入`asp`或`andorids`或`androidsp`
![image](https://user-images.githubusercontent.com/6901815/39910728-2cf3b4ac-552b-11e8-82d8-2ae6c68cd0cb.png)

**Comment by zh-avi** [comment]
1.是的，必须精确，因为按照你的想法的话，搜出来的东西就太多了（毕竟 tcmatch 是可以区配汉字拼音声母的）。
2.第二张图出现的这些项是默认的“当没有任何匹配项时，显示的内容”，可不是“莫名其妙”的东西哦。

> 如果有兴趣研究一下 AutoHotKey 的话，Runz 会有无限可能，包括你想要的效果（并不建议那样）。

对于你的问题，给你一个建议，你可以编辑 **Runz/conf/UserFileList.txt** 中关于 Android Studio Preview 的这一行，后面加上 | ASP ，比如我的火狐浏览器设置：
`file | D:\ProgramFiles\Mozilla Firefox\Firefox.exe | FF`
这样，我直接打 ff 就可以启动它了。

**Comment by zh-avi** [comment]
tcmatch 的文档，我只找到这个：https://www.ghisler.ch/board/viewtopic.php?t=22592

**Comment by wenmin92** [comment]
感觉它的搜索功能不行，最好用的还是**Launcy**，比如这种场景下，我输入`androidsp`或者`asp`，并从结果中选取`Android Studio Preview`，下次它就会将这个选择结果直接排在第一，也是用的加权算法，但是不是全局的加权算法，而是针对关键字的。它更厉害的地方在于第一次搜索的时候就能搜索到，只不过排名可能比较靠后，通过第一次选取后，排名会提前。像firefox这种，我那时候就直接`ff`搜的，不需要专门定义映射关系。
