### ISSUE TITLE
能否增加”以管理员权限执行命令“

### ISSUE THREAD

**Issue by Leoongithub** [goreliu/runz#54]
不知道在RunZ没有以管理员权限运行的前提下，能否实现这个功能，每次执行管理员权限命令都弹一次UAC是可以接受的。
另外冒号开头自动调用cmdrun，分号开头自动调用ahkrun这个功能的代码在哪一部分，如果能自定义更多的类似功能就好了。

**Comment by goreliu** [comment]
暂时不考虑。
