### ISSUE TITLE
关于匹配的问题

### ISSUE THREAD

**Issue by Leoongithub** [goreliu/runz#56]
两个关于匹配的问题：
1.bc会匹配abc和bc两个程序，但是这种情况能否无视优先级把bc放到abc的前面（从头匹配的条目优先级应该比从中间匹配的更高）。
2.输入“abc空格”，然后在保留空格的情况下更改“abc”似乎不会改变匹配的内容，这种设计是有意为之的吗？

**Comment by goreliu** [comment]
1 不支持
2 有意为之，为了方便实现
