### ISSUE TITLE
请问可以添加对的mdict支持吗?

### ISSUE THREAD

**Issue by diggerdu** [goreliu/runz#6]

**Comment by goreliu** [comment]
这个我不大清楚是否好实现，先了解一下。

**Comment by goreliu** [comment]
大概搜了下，没发现比较容易的办法，暂时不会支持，如果有相关资料也可以发一下。

**Comment by diggerdu** [comment]
开启了剪贴板监控后，按快捷键可以自动查询剪贴板内的单词。不知道能不能通过这个途径实现，最近一直比较忙，也没有太多的时间去学AHK，不好意思。
