### ISSUE TITLE
网址支持

### ISSUE THREAD

**Issue by kejlnz** [goreliu/runz#7]
如果在`[command]`下定义不带有www.前缀的网址，如：
`file | agar.io | agar`

则会出现以下报错：
![image](https://cloud.githubusercontent.com/assets/18624993/14759143/1d7f755a-08d5-11e6-906b-f1d85962d66b.png)

如果符合`AHK`函数`RUN`的网址规范加入http://，则成功打开，但条目中的网址会缺失
如：
`file | http://agar.io | agar`

![image](https://cloud.githubusercontent.com/assets/18624993/14759136/ab070c04-08d4-11e6-8f97-1203b182ed28.png)

不大熟悉`AHK`脚本，不知是不是字符串抓取时的bug

**Comment by goreliu** [comment]
确实有问题，下一个版本（1.0.9，估计今天晚些时候发布）支持 url 命令了：

```
url | agar.io
```

可以加 http://，也可以不加。

**Comment by goreliu** [comment]
1.0.9 发布了。

**Comment by kejlnz** [comment]
完美解决，精彩@goreliu

另外想问问有没有清空当前输入框的快捷键？或者每次呼出RunZ自动清空输入框的设定？

**Comment by goreliu** [comment]
清空输入框可以 Ctrl + l（L）
每次呼出 RunZ 自动清空的话，可以在配置文件设置：

```
KeepInputText=0
; 窗口隐藏时不清空编辑框内容
```

为 0。
